sudo: false

language: generic

# Cache stack installation such as GHC.
cache:
  directories:
  - $HOME/.stack

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
  - stack test --interleaved-output

notifications:
  email: false